### ISSUE TITLE
Automatically Redirect to HTTPS

### ISSUE THREAD

**Issue by aziraphale** [pronouns/main#17]
While it's lovely to see that the pronouny.xyz site supports TLS/HTTPS (I'm *so glad* that Cloudflare and Let's Encrypt have made that easy and free now!), unfortunately there appears to be no redirection to HTTPS if you visit the HTTP version, so I actually came here initially to request that you add TLS support, as it looked like you were expecting me to submit passwords (and personal details) over unencrypted channels! 😸

Of course, you also have HTST enabled on the site, so I suspect you may just not have noticed/considered this issue, as you'll now just be getting forced onto HTTPS regardless of what you type into your address bar :)

So would it be possible to enable automatic redirects to HTTPS for the site, please? 😺

Cloudflare provides an "Always Use HTTPS" option under "Crypto" these days, which I imagine will do the job. (For some reason, at work we have a custom Page Rule to achieve pretty much the exact same thing, courtesy of my predecessor, rather than using that option, so I can't totally promise that that'll work!)

Thanks - and thanks for creating this site, too! :)

**Comment by falkirks** [comment]
I just enabled this yesterday. Thanks for reporting.
