### ISSUE TITLE
Sign-Up Using Twitter Broken

### ISSUE THREAD

**Issue by aziraphale** [pronouns/main#18]
Hiya :)

It looks like the Twitter OAuth registration on the pronouny.xyz site is broken :(

(Using Chrome 71 Beta Channel, on Windows 10. I *am* using uBlock Origin as well, but that says it's not blocking anything, so that shouldn't be affecting things.)

I was able to register using the standard email/username/password form, though, so sign-up isn't entirely broken :)

When I clicked the Twitter button on the Sign-Up page, my browser made a request to `/api/auth/twitter?redirect_to=%2F`, which responded with a 302 redirect to `/server-error`. That `/server-error` page just says `Oops! Something went wrong...` and I can't find any real error details anywhere on that page, in its HTML, or its HTTP headers, so hopefully you have some error logging somewhere? 😸

If it helps, I subsequently registered as `aziraphale` (😻 Terry Pratchett), and my IPv4 address looks like `90.x.x.76`.

Sadly, I really don't have the time to look into this in any more detail (such as setting up the site on one of my own servers and checking for error messages), but hopefully it'll be easy enough for you to debug and fix - and hopefully it's not a result of Twitter deciding to hobble their OAuth API just like they did to their Streaming API the other month! >.<

Thanks!

**Comment by falkirks** [comment]
Thanks for reporting this. Sorry it's taken so long to get to it. I will try to reproduce now.

**Comment by falkirks** [comment]
I have fixed the twitter login now. Facebook is also broken, so I am going to attempt to get that working now too.

**Comment by kuzetsa** [comment]
I don't think 5c84be7b69011704d67228ff2649ac26ce208b0e fixed the issue  
(*either that or it came back for some unrelated reason*)

**Comment by falkirks** [comment]
What error do you get? Are you signing up, adding it to an account, or just signing in?

It works on my end for signing in and adding to accounts.

**Comment by kuzetsa** [comment]
> What error do you get? Are you signing up, adding it to an account, or just signing in?
> 
> It works on my end for signing in and adding to accounts.

![Imgur](https://i.imgur.com/WRitRcA.png)

^ it says:

```
Email already exists
```

but can't recover based on username or the email address associated with my twitter account (*I had just assumed it was the same error, but in hindsight might not be the same one from issue #18 - sorry about that*)

**Comment by falkirks** [comment]
I have created a new issue for this and debugged it, hopefully I can fix it shortly too.
