### ISSUE TITLE
 No matching document found for id "..." when trying to change username

### ISSUE THREAD

**Issue by iomintz** [pronouns/main#26]
## Problem steps

Change username. Click "save profile".

## Expected behavior

Username is changed

## Actual behavior

No matching document found for id "5e50cd16567be00015d5317f" version 0 modifiedPaths "__v, username, pronounTimeBest, nouns, names, lastPronounUpdateAt, updated"

like this: 
![error screen](https://user-images.githubusercontent.com/538336/75088358-c10ed080-5511-11ea-9585-e45c77c3bb9d.png)

**Comment by falkirks** [comment]
Hmmm...having trouble reproducing this one. I have changed my own username and also "5e50cd16567be00015d5317f"'s username and didn't encounter an issue. Perhaps it was a temporary database issue?
