### ISSUE TITLE
API Leaking user emails

### ISSUE THREAD

**Issue by purr** [pronouns/main#33]
Hello, I tried reaching out via email (Sent to hi@noa.dev) so I wouldn't need to make a public issue, but I never got a reply to my email. Could you please check your email so I won't need to disclose the details on here? Rather not since its regarding peoples personal information. Thanks 👍

**Comment by falkirks** [comment]
What is your email address? I think I must have missed the email or it got sent to spam.

**Comment by falkirks** [comment]
Ah I got it. Looking now.

**Comment by purr** [comment]
Thanks 👍 Apologies if my email got caught in spam

**Comment by falkirks** [comment]
I think I just missed it somehow, it was in my inbox. Thanks so much for reporting this! I will reply to the email.
