### ISSUE TITLE
Issue: Cannot add new names

### ISSUE THREAD

**Issue by fxgcxrx** [pronouns/main#34]
I used to be able to add names to my profile, but now when I type them and click add, nothing happens.

**Comment by kandiir4vr** [comment]
I've had the same problem. After I click add, the name disappears and nothing happens.

**Comment by falkirks** [comment]
@fxgcxrx @kandiir4vr What browser/device are you using?

**Comment by kandiir4vr** [comment]
I tried to do it on chrome on both my android phone and my chromebook and neither worked

**Comment by falkirks** [comment]
@kandiir4vr What is your pronouny username? You can also email me it at hi@noa.dev if you'd rather not comment it here.

**Comment by fxgcxrx** [comment]
I use a Mac with google chrome/firefox. I also use an iPhone. 

My pronouny username is fagcore.

**Comment by ODeorain** [comment]
I am now experiencing this problem on Opera.  I was able to enter about 3 names successfully before suddenly they all disappeared.  I now cannot add any more and none are displaying on my account.

**Comment by falkirks** [comment]
This is now fixed in 8121764edc70c26de134efbe5e53d676942e104b! This was actually being caused by people having duplicate names.
