### ISSUE TITLE
Password reset email issue / Login problems

### ISSUE THREAD

**Issue by ddigii** [pronouns/main#52]
Hiya, 

I made a pronouny recently but have had trouble signing in with my password on my phone; The site forced me to log out yesterday evening, and when I try to log back in I get the “invalid username or password” error.

I clicked the Forgot Password button (and did the same on my phone), but I haven’t received an e-mail with further instruction for either of those requests. 

The email used was digi@next7gen.com, and my username on pronouny is “ddigi”.

Any help with this would be very appreciated :)

Thanks,

Digi

**Comment by falkirks** [comment]
Hey! I just checked our email service and it is saying the password reset emails were delivered to you. Perhaps they are in your spam folder? If you can't find it you can email me at hi@noa.dev and I can send you a copy manually.

**Comment by ddigii** [comment]
Found them - turns out I was having an email issue at my end! Thanks for the reply 👍
